export const PERMISSIONS = [
  {
    name: 'Crear',
    description: 'Permite registrar nuevos datos en el sistema',
    action: 'create',
    resource: 'global',
    type: 'global',
    created: new Date(),
    modified: new Date(),
    isActive: true,
  },
  {
    name: 'Buscar',
    description: 'Permite consultar y filtrar',
    action: 'read',
    resource: 'posts',
    type: 'global',
    created: new Date(),
    modified: new Date(),
    isActive: true,
  },
  {
    name: 'Editar',
    description: 'Permite modificar un contenido',
    action: 'update',
    resource: 'post',
    type: 'global',
    created: new Date(),
    modified: new Date(),
    isActive: true,
  },
  {
    name: 'Eliminar',
    description: 'Permite borrar o eliminar de una tabla',
    action: 'delete',
    resource: 'post',
    type: 'global',
    created: new Date(),
    modified: new Date(),
    isActive: false,
  },
];
